# Generated by Django 2.0 on 2018-01-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='posted',
        ),
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.CharField(blank=True, max_length=260, unique=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='posted_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='subtitle',
            field=models.CharField(blank=True, max_length=260, unique=True),
        ),
    ]
