# Generated by Django 2.0 on 2018-01-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180118_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_cat',
            field=models.CharField(blank=True, max_length=260, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='image_ind',
            field=models.CharField(blank=True, max_length=260, unique=True),
        ),
    ]
